spring.application.name=RestAPIFurb
server.servlet.context-path=/RestAPIFurb
spring.datasource.url=jdbc:h2:mem:resapifurb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
jwt.secret=MinhaChaveMuitoSecretaParaJWT123456
jwt.expiration-ms=3600000
